/**
 * @file src/lang/interpreter.ts
 * 
 * This file implements the interpreter for the Tacit language.
 * 
 * The interpreter is responsible for executing bytecode generated by the parser.
 * It handles the main execution loop, opcode dispatch, error handling, and function calls.
 * The interpreter maintains the VM state during execution, including the instruction
 * pointer, stack, and return stack.
 * 
 * The interpreter provides three main entry points:
 * - execute: Runs bytecode starting from a specific address
 * - executeProgram: Parses and executes a string of Tacit code
 * - callTacitFunction: Calls a Tacit function and returns to the caller
 */

import { executeOp } from '../ops/builtins';
import { vm } from '../core/globalState';
import { parse } from './parser';
import { toTaggedValue, Tag } from '../core/tagged';
import { Tokenizer } from './tokenizer';

import { SEG_CODE } from '../core/memory';

/**
 * Executes Tacit bytecode starting from a specific address.
 * 
 * This function implements the main execution loop of the Tacit VM. It:
 * 1. Sets the instruction pointer to the start address
 * 2. Fetches and executes opcodes in a loop until execution is halted
 * 3. Handles errors during execution with detailed diagnostics
 * 4. Resets the compiler state after execution
 * 
 * The execution can be configured to break when reaching a specific instruction
 * address, which is useful for debugging and implementing breakpoints.
 * 
 * @param {number} start - The starting address (instruction pointer) for execution
 * @param {number} [breakAtIP] - Optional address at which to halt execution
 * @throws {Error} If an invalid opcode is encountered or execution fails
 */
export function execute(start: number, breakAtIP?: number): void {
  // Initialize execution state
  vm.IP = start;
  vm.running = true;
  
  // Main execution loop
  while (vm.running) {
    // Check for breakpoint
    if (breakAtIP !== undefined && vm.IP === breakAtIP) {
      vm.running = false;
      break;
    }

    // Fetch the next opcode
    const functionIndex = vm.nextOpcode();
    if (vm.debug) console.log({ functionIndex }, vm.IP - (functionIndex >= 128 ? 2 : 1));
    
    try {
      // Validate the opcode
      if (functionIndex < 0 || functionIndex >= 32768) {
        const originalIP = vm.IP - (functionIndex >= 128 ? 2 : 1);
        const rawValue = vm.memory.read8(SEG_CODE, originalIP);
        throw new Error(`Invalid opcode: ${rawValue}`);
      }

      // Execute the opcode
      executeOp(vm, functionIndex);
    } catch (error) {
      // Handle execution errors with detailed diagnostics
      const stackState = JSON.stringify(vm.getStackData());
      const errorMessage =
        `Error executing word (stack: ${stackState})` +
        (error instanceof Error ? `: ${error.message}` : '');
      if (vm.debug) console.log((error as Error).stack);
      vm.compiler.reset();
      vm.compiler.preserve = false;
      console.log((error as Error).stack);
      throw new Error(errorMessage);
    }
  }
  
  // Clean up after execution
  vm.compiler.reset();
  vm.compiler.preserve = false;
}

/**
 * Parses and executes a string of Tacit code.
 * 
 * This function provides a high-level entry point for running Tacit programs.
 * It tokenizes and parses the input code, then executes the resulting bytecode.
 * 
 * @param {string} code - The Tacit source code to execute
 */
export function executeProgram(code: string): void {
  // Parse the code into bytecode
  parse(new Tokenizer(code));
  
  // Execute the bytecode from the beginning of the compiled program
  execute(vm.compiler.BCP);
}

/**
 * Executes a specific block of Tacit code using the current global VM state.
 * 
 * This function allows calling a Tacit function from JavaScript code. It:
 * 1. Saves the current execution context (IP and BP) on the return stack
 * 2. Sets up a new execution context for the called function
 * 3. Executes the function until it returns via an 'exit' operation
 * 4. Restores the original execution context
 * 
 * Unlike executeProgram, this function does not reset the interpreter state,
 * allowing it to be used within an ongoing execution. This is particularly
 * useful for implementing foreign function interfaces and for the re-entrant
 * execution of resumable functions.
 * 
 * @param {number} codePtr - The starting address (instruction pointer) of the Tacit code to execute
 */
export function callTacitFunction(codePtr: number): void {
  // Save the current instruction pointer for return
  const returnIP = vm.IP;
  
  // Set up the call frame on the return stack
  vm.rpush(toTaggedValue(returnIP, Tag.CODE)); // Save return address
  vm.rpush(vm.BP);                             // Save base pointer
  vm.BP = vm.RP;                               // Set new base pointer
  
  // Jump to the function code and execute
  vm.IP = codePtr;
  vm.running = true;
  execute(vm.IP);
  
  // Verify proper return and restore IP if needed
  if (vm.IP !== returnIP) {
    console.warn(`Warning: IP mismatch after function call. Expected ${returnIP}, got ${vm.IP}`);
    vm.IP = returnIP;
  }
}
